### PR TITLE
fix: display user name in posts

### LINKED ISSUE #90: Feat: Username display feature
### What feature?

Currently the userId is exposed for a user when we see a profile. To fix that, a username should be there as it will be easy for the users instead of userId.

### Add screenshots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
## Related Issue

Closes #90 

## Description

Earlier post ID was showing in place of username. So, I fixed that by getting current signed in user. 

## Screenshots

Screenshot 2024-01-03 at 19 30 08

### CODE REVIEW

File: src/components/core/posts/SinglePost.tsx [hunk 1]
```diff
@@ -112,7 +126,7 @@ export default function SinglePost({
           <Image src="/assets/user.png" alt="user" width={40} height={40} />
         </div>
         <div>
-        <h5 className="font-medium text-md">{singlePost && singlePost?.accountId}</h5>
+        <h5 className="font-medium text-md">{user.name}</h5>
```
Comment (Sanchitbajaj02) [inline src/components/core/posts/SinglePost.tsx:129]: I think it should be according to the user post and not according to the current user. One solution is that you are getting the `accountId` from the singlePost object, pass this id to the api which fetches the username/fullName

**Review by Sanchitbajaj02 — CHANGES_REQUESTED** [review]

**Comment by Vidip-Ghosh** [comment]
Screenshot 2024-01-07 at 15 48 41
The changes made.

**Review by Sanchitbajaj02 — APPROVED** [review]
